language: node_js
node_js:
    - "5"
    - "5.1"
before_script:
    - npm install -g gulp
compiler: clang-3.6
env:
    - CXX=g++4.8
addons:
    apt:
        sources:
            - ubuntu-tolchain-r-test
        packages:
            - g++4.8